활동/스크래치/Basic/V - FE 2차
team-monolith-product/scratch-gui pull request #1
Opened 2023-12-15 02:21 UTC by paulkim3151

# [활동/스크래치/Basic/V - FE 2차](https://www.notion.so/team-mono/Basic-V-FE-2-53723b70830a4703a4430f8b4619262e)

- [x] MenuBar 숨기는 props 추가
- [x] Stage Header에 저장 버튼 및 저장 상태 텍스트 추가
- [x] Project Asset 저장시 Response를 확인하는 로직 삭제

2023-12-15 02:22 UTC, paulkim3151 commented on package.json
개발시에는 `npm run watch`를 통해 개발하고, publish 할때는 `npm run build` 통해서 production 빌드가 되도록 수정했습니다.

2023-12-15 02:22 UTC, paulkim3151 commented on .vscode/settings.json
ESLint를 formatter로 사용할 수 있도록 하는 설정

2023-12-15 02:23 UTC, paulkim3151 commented on src/lib/project-saver-hoc.jsx
S3에는 response를 설정할 수 없으므로, response를 체크하는 로직을 삭제합니다.

2023-12-15 02:29 UTC, paulkim3151 commented on src/lib/project-saver-hoc.jsx
> +                    ).then(() => {
Codle에서 Asset 서버로 사용하고 있는 S3에는 response를 설정할 수 없으므로, response를 체크하는 로직을 삭제합니다.

2023-12-15 02:45 UTC, shcshcshc requested changes
혹시 조건부 렌더링이 react16에서는 안되나요?

2023-12-15 02:45 UTC, shcshcshc commented on src/components/gui/gui.jsx
> +                {showMenuBar ? (
```suggestion
                {showMenuBar && (
```
하고 밑에 null 지우기

2023-12-15 02:45 UTC, shcshcshc commented on src/components/gui/gui.jsx
> +                    })}
이부분 이해가 안되는데 (의도는 유추되지만) 어떤식으로 들어가는건지 설명해주실수있나요?

2023-12-15 02:45 UTC, shcshcshc commented on src/components/stage-header/stage-header.jsx
> +                        {stageSizeMode === STAGE_DISPLAY_SIZES.large ? (
이 부분과 하위요소도 마찬가지로 삼항연산자 대신에 && 사용

2023-12-15 02:46 UTC, paulkim3151 commented on src/components/gui/gui.jsx
> +                {showMenuBar ? (
그건 아닌데, 이게 typescript가 아니다 보니, showMenuBar에 어떠한 형태든 들어올수 있다고 생각되어서 이런식으로 구성한 것 같습니다. (이 레포지토리의 Code Convention입니다.)

2023-12-15 02:48 UTC, shcshcshc commented on src/components/gui/gui.jsx
> +                {showMenuBar ? (
어떠한 형태가 들어오든 동작은 같을거라고 예상되는데 Code Convention이라면 이해가 됩니다

2023-12-15 02:48 UTC, paulkim3151 commented on src/components/gui/gui.jsx
> +                {showMenuBar ? (
단적인 예로, showMenuBar가 boolean이 아닌, `0` 이 들어오면 `0 && <Component/>`의 값은 `0`이 되어서 화면에 0이 출력됩니다.

2023-12-15 02:51 UTC, shcshcshc commented on src/components/gui/gui.jsx
> +                {showMenuBar ? (
요지는 showMenuBar가 boolean으로 보장되어 있지 않다는거군요 알겠습니다

2023-12-15 02:52 UTC, paulkim3151 commented on src/components/gui/gui.jsx
> +                    })}
https://www.npmjs.com/package/classnames docs에서, key-value 형태로 넣을 수 있고,
 value가 false 이면 해당 key에 해당하는 classnames은 삽입되지 않는 것으로 보입니다.

 css가 어떻게 styles로 변환되는지는 저도 아직 파악은 못했고, 다른 코드 컨벤션에 따라 맞췄습니다.

2023-12-15 02:54 UTC, shcshcshc approved these changes

2023-12-19 01:19 UTC, a3626a approved these changes

2024-01-22 05:21 UTC, merged