Feature/scratch observable
team-monolith-product/scratch-gui pull request #2
Opened 2024-02-02 06:02 UTC by paulkim3151

# [활동/스크래치/O - FE](https://www.notion.so/team-mono/O-FE-41bd3598aea94370aa74aa2641d02bbf)
- [x]  ProjectIdUpdatorHOC 추가
- [x]  `canSave` props로 저장버튼 노출 여부 결정
- [x]  FullScreen 토글 버튼 노출 로직 수정
- [x]  `RELOAD_PROJECT` action 추가

2024-02-02 06:52 UTC, paulkim3151 commented on src/codle/project-id-updator-hoc.jsx
projectId가 변경될때마다 setProjectId를 dispatch 하도록 만들어주는 HOC

2024-02-05 03:57 UTC, a3626a commented on src/components/stage-header/stage-header.jsx
> +        const stageButton = isPlayerOnly ? null : showBranding ? (
이건 `showBranding` 속성을 전달해서 숨기면 되는 것 아닌가요? 이 조건문이 추가되어야 한 이유는 무엇인가요?

2024-02-05 04:46 UTC, paulkim3151 commented on src/components/stage-header/stage-header.jsx
> +        const stageButton = isPlayerOnly ? null : showBranding ? (
stageButton 영역은 표시된 다음 영역입니다.

![image](https://github.com/team-monolith-product/scratch-gui/assets/33952999/0de11a61-f483-4a31-9d71-9d03bc3a878f)


`isPlayerOnly=true` 모드에서는 isFullScreen에 따라서 다음 두가지 화면이 있습니다.
### isFullScreen = false일때
![image](https://github.com/team-monolith-product/scratch-gui/assets/33952999/f062b5fd-1c84-451a-8e8a-883b90cae827)

### isFullScreen = true일때
![image](https://github.com/team-monolith-product/scratch-gui/assets/33952999/fe637ce4-3fab-4284-8c7c-4fef7b9afcbe)


isFullScreen = false 인 경우는 UX 상으로 전혀 필요가 없는 모드이고, 태희님께서는 isPlayerOnly 모드일때는 항상 FullScreen으로 세팅하고, 전체화면 나가는 해당 버튼을 숨겨달라고 말씀해주셨습니다.

그래서 저런 조건문이 추가되어야 했습니다.

2024-02-06 03:52 UTC, a3626a requested changes

2024-02-06 03:52 UTC, a3626a commented on src/components/stage-header/stage-header.jsx
> +        const stageButton = isPlayerOnly ? null : showBranding ? (
자세한 설명 감사드립니다. 그런데 설명해주신 내용이 왜 'showBranding'을 쓰면 안되는 가에 대해서는 충분한 설명이 되지 않습니다.

`scratch-gui`는 fork 원본과 차이를 줄이고, 잠재적으로 원본에 PR을 올릴 수 있는 구조를 취하는 것이 좋습니다. 따라서 우리(팀모노리스)의 비즈니스 로직이 `scratch-gui`에 포함되는 것은 좋지 않다고 생각됩니다. 그렇기 때문에 저는 기존에 `showBranding` 속성을 활용하여 Button 영역을 제어할 수 있다면, 그게 더 좋다고 생각합니다. (대신 scratch-react에서 showBranding에 적절한 값을 전달해야함) 예를 들어 `canSave` 등과 같은 변경은 비즈니스 로직에 독립적이고 일반적인 기능 추가라서 아주 훌륭하다고 생각합니다.

2024-02-07 00:26 UTC, paulkim3151 commented on src/components/stage-header/stage-header.jsx
> +        const stageButton = isPlayerOnly ? null : showBranding ? (
말씀하신 포인트는 이해했습니다.
그러나 `showBranding`은 true일때 스크래치 로고를 노출하고, false일때는 전체화면 버튼을 노출하는 flag입니다.
스크래치 코드를 수정하지 않고 현재 요구사항을 반영하는 건 어려울것 같습니다.

2024-02-07 00:38 UTC, paulkim3151 commented on src/components/stage-header/stage-header.jsx
> +        const stageButton = isPlayerOnly ? null : showBranding ? (
그리고 코드를 추가적으로 더 읽어 보았는데, `showBranding` 속성은 최상위 GUI 컴포넌트에서 props 전달되는 값이 아니고, redux state에서 받아오는데, 이 값을 바꿀수 있는 action이 없고, init 할때만 세팅할 수 있도록 되어있습니다.
이 로직은 저희가 사용해야할 로직과는 맞지 않아서, 수정하지 않고는 반영하기 어렵습니다.

2024-02-07 00:42 UTC, a3626a commented on src/components/stage-header/stage-header.jsx
> +        const stageButton = isPlayerOnly ? null : showBranding ? (
그러면 보다 비즈니스에 독립적인 구조로 수정해주실 수 있을까요?

2024-02-07 01:43 UTC, paulkim3151 commented on src/components/stage-header/stage-header.jsx
> +        const stageButton = isPlayerOnly ? null : showBranding ? (
수정했습니다.

2024-02-07 01:45 UTC, a3626a approved these changes

2024-02-07 02:08 UTC, merged